### ISSUE TITLE
units in notebook 4_PairingOutputToPICASO

### ISSUE THREAD

**Issue by jgizis** [natashabatalha/virga#19]
In cell 11 of notebook 4_PairingOutputToPICASO (the Looking at Mie parameters section), the plots are labeled as microns and the discussion below says they are microns too, but they start at ~3000 not 0.3.  I think this is because the wavelengths are multiplied by 1e4 ...  Maybe it used to be converted to Angstroms? 

```

qfig.line(1e4*wave[:,0], g_qscat[:,ind]/qscat[:,ind])
wfig.line(1e4*wave[:,0], qscat[:,ind]/qext[:,ind])

```

ps. The notebooks are great. This is all so amazing.

**Comment by natashabatalha** [comment]
Fixed ! https://github.com/natashabatalha/virga/pull/23/commits/4e23cba9124e0eb8afa8e22bf40346d6f0e0eb83 

Sorry this took so long!
