### ISSUE TITLE
Bug: `virga.justdoit.condensation_t` returns an array of constant values

### ISSUE THREAD

**Issue by logan-pearce** [natashabatalha/virga#35]
`virga.pvaps.NH3` still returns the correct value, but when using `virga.justdoit.recommend_gases` the NH3 curve is a vertical line.
![Screen Shot 2023-08-16 at 2 00 41 PM](https://github.com/natashabatalha/virga/assets/27641243/86f67fa4-3479-454a-815e-066c26baac74)

**Comment by natashabatalha** [comment]
Fixed https://github.com/natashabatalha/virga/commit/db08240173df1a2f12041bc3c02aaaced51f5e00
