### ISSUE TITLE
Question on 1_GettingStarted. Lack of .refrind folder.

### ISSUE THREAD

**Issue by cbartier** [natashabatalha/virga#40]
I am working through the first tutorial with the goal of creating ".mie" files. In the tutorial it says that virga comes with a folder with files that end in .refrind, but I do not have .refrind folder. Below is the error when I run the cell to get the complex refractive indices and my virga folder. Thank you for your time! 
<img width="1123" alt="Screenshot 2024-03-04 at 12 27 04 PM" src="https://github.com/natashabatalha/virga/assets/113122583/a9c82a90-0e67-4a90-b6cd-08e2b1840915">
<img width="753" alt="Screenshot 2024-03-04 at 12 27 23 PM" src="https://github.com/natashabatalha/virga/assets/113122583/3a274f4a-44fd-4b42-92cf-cb5cfe8f6564">

**Comment by aetherspritee** [comment]
You can grab the refractive indices from [here](https://zenodo.org/records/3758538#.Xp4w-1NKjOQ). Make sure to adjust the `refrind_dir` variable such that it points to the directory including the downloaded data.

**Comment by cbartier** [comment]
@aetherspritee Thank you! I got it.
